INSERT INTO `person` VALUES
( NULL, 'Domenic ', 'rodriguez', 'you@dot.com', '', 'N.W.', 'Somewhere', 'CA', 'Mexico', '1234567', 'director ', 'NSA', 'hash9876' )
( NULL, 'Cesar ', 'Laveta', 'orange@gmail.com', '', '75 Fifth Street', 'Green Wood', 'FL', 'Canada', '5555555', 'other', 'NASA', 'hash2' )
( NULL, 'Jay ', 'Charmain', 'me@dot.com', '', '4926 SW Park St', 'Green Wood', 'ND', 'Mexico', '5555555', 'actor', 'Barnes & Noble', 'hash4' )
( NULL, 'Santos ', 'Fatima', 'me@dot.com', '', '4926 SW Park St', 'Tacoma', 'ID', 'UK', '8793311', 'director ', 'The Coca-Cola Company', 'hash23' )
( NULL, 'Irving ', 'Charmain', 'me@dot.com', '', 'One Financial Plaza 777 Main Street', 'Green Wood', 'ND', 'Canada', '5555555', 'actor', '2K Games', 'hash23' )
( NULL, 'Jeff', 'rodriguez', 'me@dot.com', '', 'One Financial Plaza 777 Main Street', 'Springfield', 'TX', 'US', '5555555', 'assistant', 'Ameriprise Financial', 'hash3' )
( NULL, 'Chas', 'Laveta', 'you@dot.com', '', '4926 SW Park St', 'Somewhere', 'OR', 'Mexico', '1234567', 'other', 'CIA', 'hash3' )
( NULL, 'Branden ', 'zoidberg', 'orange@gmail.com', '', '1625 Broadway', 'Seattle', 'VT', 'Canada', '5555555', 'director ', 'CNET', 'hash1' )
( NULL, 'Jay ', 'Charmain', 'me@dot.com', '', '75 Fifth Street', 'Green Wood', 'ND', 'UK', '8793311', 'assistant', '2K Games', 'hash1' )
( NULL, 'Jeff', 'Charmain', 'you@dot.com', '', 'One Financial Plaza 777 Main Street', 'Green Wood', 'TX', 'Canada', '1234567', 'assistant', 'FBI', 'hash4' )
( NULL, 'Santos ', 'fry', 'me@dot.com', '', '4926 SW Park St', 'Seattle', 'OR', 'Mexico', '5555555', 'other', 'Ameriprise Financial', 'hash9876' )
( NULL, 'Jeff', 'Charmain', 'me@dot.com', '', 'One Financial Plaza 777 Main Street', 'Springfield', 'TX', 'Mexico', '8793003', 'actor', 'Citrix Systems', 'hash2' )
( NULL, 'philip', 'zoidberg', 'orange@gmail.com', '', 'PO Box 110801', 'Green Wood', 'WN', 'Canada', '8793003', 'assistant', 'CNET', 'hash3' )
( NULL, 'Santos ', 'Laveta', 'orange@gmail.com', '', 'Suite 1200', 'Seattle', 'TX', 'Mexico', '1234567', 'other', 'UPS', 'hash3' )
( NULL, 'Waldo ', 'Laveta', 'me@dot.com', '', '75 Fifth Street', 'Tacoma', 'WN', 'Canada', '1234567', 'assistant', 'Broadcom', 'hash2' )
( NULL, 'Jeff', 'zoidberg', 'you@dot.com', '', 'PO Box 110801', 'Springfield', 'WN', 'Mexico', '8793003', 'director ', 'The Coca-Cola Company', 'hash1' )
( NULL, 'Cesar ', 'fry', 'orange@gmail.com', '', 'Suite 1200', 'Springfield', 'TX', 'Canada', '8793311', 'director ', 'Barnes & Noble', 'hash23' )
( NULL, 'Chas', 'Fatima', 'me@dot.com', '', 'Suite 1200', 'Tacoma', 'VT', 'US', '1234567', 'assistant', 'Citrix Systems', 'hash2' )
( NULL, 'Branden ', 'Laveta', 'you@dot.com', '', 'N.W.', 'Springfield', 'TX', 'Mexico', '1234567', 'director ', 'UPS', 'hash2' )
( NULL, 'bender', 'Fatima', 'you@dot.com', '', '75 Fifth Street', 'Green Wood', 'WN', 'UK', '1234567', 'director ', 'NASA', 'hash1' )

INSERT INTO `production` VALUES
( NULL, 'Seussical', 'Barbu Delavrancea', 'CNET', '12/23/2012', '1/354/123' )
( NULL, 'Rocky Horror Show', 'Alexandre Bisson', 'NASA', '43/234/543', '43/234/543' )
( NULL, 'Oklahoma!', 'William Rufus Chetwood', 'FBI', '12/23/2012', '12/23/2012' )
( NULL, 'Rosencrantz and Guildenstern Are Dead', 'George Francis Abbott', 'Citrix Systems', '43/234/543', '43/234/543' )
( NULL, 'Seussical', 'Ramvriksh Benipuri', 'FBI', '12/23/2012', '12/23/2012' )
( NULL, 'Seussical', 'William Rufus Chetwood', 'UPS', '12/23/2012', '43/234/543' )
( NULL, 'Guys and Dolls', 'Barbu Delavrancea', 'BrightPoint', '1/354/123', '43/234/543' )
( NULL, 'Oklahoma!', 'Ernst Barlach', 'NASA', '1/354/123', '324/98/07' )
( NULL, 'Rosencrantz and Guildenstern Are Dead', 'Tom Stoppard', 'NSA', '43/234/543', '324/98/07' )
( NULL, 'Rocky Horror Show', 'William Rufus Chetwood', 'BrightPoint', '324/98/07', '1/354/123' )
( NULL, 'Arsenic and Old Lace', 'Tom Stoppard', 'NSA', '12/23/2012', '43/234/543' )
( NULL, 'Guys and Dolls', 'Alexandre Bisson', 'UPS', '324/98/07', '43/234/543' )
( NULL, 'Rocky Horror Show', 'George Francis Abbott', 'Barnes & Noble', '324/98/07', '1/354/123' )
( NULL, 'A Streetcar Named Desire', 'Nick Enright', 'CNET', '12/23/2012', '324/98/07' )
( NULL, 'The Wiz', 'Ernst Barlach', 'The Coca-Cola Company', '1/354/123', '12/23/2012' )
( NULL, 'Rocky Horror Show', 'Ernst Barlach', 'Ameriprise Financial', '43/234/543', '12/23/2012' )
( NULL, 'A Streetcar Named Desire', 'Tom Stoppard', 'UPS', '12/23/2012', '12/23/2012' )
( NULL, 'The Wiz', 'Alexandre Dumas', 'Broadcom', '12/23/2012', '1/354/123' )
( NULL, 'Oklahoma!', 'Alexandre Dumas', 'Citrix Systems', '324/98/07', '1/354/123' )
( NULL, 'Seussical', 'Ramvriksh Benipuri', 'UPS', '43/234/543', '43/234/543' )

INSERT INTO `prop` VALUES
( NULL, 'cat', 'covered in ants', NULL, 'tall' )
( NULL, 'shoes', '', NULL, 'small' )
( NULL, 'chair', 'covered in ants', NULL, 'heavy' )
( NULL, 'shirt', '', NULL, 'small' )
( NULL, 'chair', 'sharp and pointy', NULL, 'sticky' )
( NULL, 'shirt', '', NULL, 'tall' )
( NULL, 'table', 'covered in ants', NULL, 'orange' )
( NULL, 'desk', '', NULL, 'purple' )
( NULL, 'shoes', '', NULL, 'small' )
( NULL, 'chair', '', NULL, 'heavy' )
( NULL, 'table', 'covered in ants', NULL, 'sticky' )
( NULL, 'cat', 'covered in ants', NULL, 'orange' )
( NULL, 'dog', 'sharp and pointy', NULL, 'heavy' )
( NULL, 'cat', 'covered in ants', NULL, 'set' )
( NULL, 'chair', 'sharp and pointy', NULL, 'set' )
( NULL, 'chair', 'sharp and pointy', NULL, 'tall' )
( NULL, 'table', 'covered in ants', NULL, 'purple' )
( NULL, 'bench', 'covered in ants', NULL, 'set' )
( NULL, 'cat', 'covered in ants', NULL, 'red' )
( NULL, 'shirt', 'covered in ants', NULL, 'sticky' )

INSERT INTO `category` VALUES
( NULL, 'set', 'upstairs' )
( NULL, 'light', 'store room' )
( NULL, 'furnature', 'closet2' )
( NULL, 'clothing', 'closet2' )
( NULL, 'clothing', 'upstairs' )
( NULL, 'light', 'floor' )
( NULL, 'clothing', 'closet1' )
( NULL, 'set', 'closet1' )
( NULL, 'set', 'upstairs' )
( NULL, 'furnature', 'store room' )
( NULL, 'light', 'store room' )
( NULL, 'furnature', 'closet1' )
( NULL, 'light', 'closet2' )
( NULL, 'clothing', 'floor' )
( NULL, 'clothing', 'upstairs' )
( NULL, 'clothing', 'closet2' )
( NULL, 'clothing', 'upstairs' )
( NULL, 'furnature', 'store room' )
( NULL, 'furnature', 'floor' )
( NULL, 'light', 'closet1' )

